title: Demo notes repo 
thene: jekyll-theme-cayman  

## Keyboard shortcuts 
Shortcuts I frequently choose: 
- Ctrl-C (copy) 
- Ctrl-V (paste) 
- Win-D (shows desktop)

Shortcuts I would like to start using: 
- Ctrl-Z (undo) 
- Ctrl-A (select all) 
- Ctrl-S (saves a document you are working on) 

## Search Experiments
Try searching for the word "line"

```
Line
line
lines
line 5
line-7
line72
line73.4
end of line
end-of-line
outline
linear
```